# -*- coding: utf-8 -*-
"""a1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N9U5x1HuJkQirnw5ueyhHmyvbaBd95cC
"""

print("3개의 정수값을 입력하시오")
n1 = int(input("n1의 정수값을 입력: "))
n2 = int(input("n1의 정수값을 입력: "))
n3 = int(input("n1의 정수값을 입력: "))


total = n1 + n2 + n3;
average = total /3 ;
print(average)